source "http://rubygems.org"
gem "bundler"
#gem "cukesparse"
#gem "yard"
gem "rake"
gem "ci_reporter"
gem "cucumber"
gem "rspec"
gem "selenium"
# then run "selenium install"
gem "selenium-webdriver"
gem "addressable"
gem "win32-service"
#gem "nokogiri"
#gem "xml-simple"
#gem "ffi"
#gem "require_all"
#gem "pry"